# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\VICFLEPIS\Desktop\MC_Sever_GUI\gui\kehuduan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1481, 920)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*[myclass=help]{\n"
"border:0px;\n"
"color:rgb(14, 191, 255);\n"
"}\n"
"*[myclass=close]:hover{\n"
"border:0px;\n"
"background:rgb(255, 0, 0);\n"
"}\n"
"*[myclass=min]:hover{\n"
"border:0px;\n"
"background:rgb(134, 134, 134)\n"
"}\n"
"*[myclass=fullscreen]:hover{\n"
"border:0px;\n"
"background:rgb(134, 134, 134)\n"
"}\n"
"*[myclass=help]:hover{\n"
"border:0px;\n"
"background:rgb(134, 134, 134);\n"
"color:rgb(79, 223, 255)\n"
"}\n"
"*[myclass=di_ceng]{\n"
"background: rgb(85, 85, 85);\n"
"}\n"
"\n"
"*[myclass=close]{\n"
"image: url(:/gui/window_close_focus2x.png);\n"
"}\n"
"*[myclass=min]{\n"
"image:url(:/gui/window_minimize_focus2x.png);\n"
"}\n"
"*[myclass=fullscreen]{\n"
"image:url(:/gui/checkbox_unchecked_focus2x.png);\n"
"}\n"
"*[myclass=titlebar]{\n"
"background: rgb(65, 65, 65);\n"
"}\n"
"*[myclass=searchbox]{\n"
"border:0;\n"
"background:rgb(94, 94, 94)\n"
"}\n"
"*[myclass=searchbox]:hover{\n"
"border:0;\n"
"background:rgb(198, 198, 198)\n"
"}\n"
"*[myclass=op]{\n"
"background: rgb(65, 65, 65);\n"
"}\n"
"*[myclass=useravatar]{\n"
"image:url(:/gui/OIP-C.jpg)\n"
"}\n"
"*[myclass=username]{\n"
"border:0px;\n"
"color:white;\n"
"background:rgb(52, 52, 52);\n"
"}\n"
"*[myclass=userinfo]{\n"
"border:0px;\n"
"color:white;\n"
"image:url(:/gui/avatar.png);\n"
"background:rgb(52, 52, 52);\n"
"}\n"
"*[myclass=userloginout]{\n"
"border:0px;\n"
"color:white;\n"
"image: url(:/gui/loginout.png);\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=ctrlsever]{\n"
"border:0px;\n"
"color:white;\n"
"image:url(:/gui/ctrlsever.png);\n"
"background-color:rgb(52, 52, 52);\n"
"}\n"
"*[myclass=history]{\n"
"border:0px;\n"
"color:white;\n"
"image: url(:/gui/history.png);\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=settings]{\n"
"border:0px;\n"
"color:white;\n"
"image:url(:/gui/settings.png);\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=username]{\n"
"border:0px;\n"
"color:white;\n"
"}\n"
"*[myclass=userinfo]:hover{\n"
"border:0px;\n"
"background-color:rgb(0, 160, 163);\n"
"}\n"
"*[myclass=userloginout]:hover{\n"
"border:0px;\n"
"color:red;\n"
"background:rgb(0, 160, 163);\n"
"}\n"
"*[myclass=ctrlsever]:hover{\n"
"border:0px;\n"
"background:rgb(0, 160, 163);\n"
"}\n"
"*[myclass=history]:hover{\n"
"border:0px;\n"
"background:rgb(0, 160, 163);\n"
"}\n"
"*[myclass=settings]:hover{\n"
"border:0px;\n"
"background:rgb(0, 160, 163);\n"
"}\n"
"*[myclass=search]{\n"
"border:0;\n"
"color:rgb(0, 255, 255);\n"
"image:url(:/gui/search.png);\n"
"background:rgb(94, 94, 94)\n"
"}\n"
"*[myclass=search]:hover{\n"
"border:2 solid rgb(0, 255, 255);\n"
"color:rgb(0, 255, 255);\n"
"background:rgb(94, 94, 94)\n"
"}\n"
"*[myclass=guildtext]{\n"
"color:rgb(170, 255, 255);\n"
"}\n"
"*[myclass=guildtext2]{\n"
"color:rgb(0, 166, 255);\n"
"}\n"
"*[myclass=about]{\n"
"color:rgb(89, 134, 131);\n"
"}\n"
"*[myclass=license]{\n"
"color:rgb(89, 134, 131);\n"
"}\n"
"*[myclass=about]:hover{\n"
"color:rgb(170, 255, 255);\n"
"}\n"
"*[myclass=license]:hover{\n"
"color:rgb(170, 255, 255);\n"
"}\n"
"*[myclass=opear1]{\n"
"image:url(:/gui/nosever.png)\n"
"}\n"
"*[myclass=tip1]{\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"*[myclass=open]{\n"
"border:0px;\n"
"image:url(:/gui/open.png);\n"
"color:white;\n"
"border-radius: 12px;\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=book]{\n"
"border:0px;\n"
"image:url(:/gui/help.png);\n"
"color:white;\n"
"border-radius: 12px;\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=feedback]{\n"
"border:0px;\n"
"color:white;\n"
"image:url(:/gui/feedback.png);\n"
"border-radius: 12px;\n"
"background:rgb(52, 52, 52)\n"
"}\n"
"*[myclass=open]:hover{\n"
"border:0px;\n"
"border-radius: 12px;\n"
"background:rgb(107, 107, 107);\n"
"}\n"
"*[myclass=book]:hover{\n"
"border:0px;\n"
"border-radius: 12px;\n"
"background:rgb(107, 107, 107);\n"
"}\n"
"*[myclass=feedback]:hover{\n"
"border:0px;\n"
"border-radius: 12px;\n"
"background:rgb(107, 107, 107);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.di_ceng = QtWidgets.QWidget(self.centralwidget)
        self.di_ceng.setGeometry(QtCore.QRect(0, 0, 1481, 931))
        self.di_ceng.setObjectName("di_ceng")
        self.titlebar = QtWidgets.QFrame(self.di_ceng)
        self.titlebar.setGeometry(QtCore.QRect(0, 0, 1481, 51))
        self.titlebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar.setObjectName("titlebar")
        self.winbutton = QtWidgets.QFrame(self.titlebar)
        self.winbutton.setGeometry(QtCore.QRect(1280, 0, 201, 51))
        self.winbutton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.winbutton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.winbutton.setObjectName("winbutton")
        self.help = QtWidgets.QPushButton(self.winbutton)
        self.help.setGeometry(QtCore.QRect(0, 0, 51, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(36)
        self.help.setFont(font)
        self.help.setFlat(True)
        self.help.setObjectName("help")
        self.fullscreen = QtWidgets.QPushButton(self.winbutton)
        self.fullscreen.setGeometry(QtCore.QRect(50, 0, 51, 51))
        self.fullscreen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fullscreen.setText("")
        self.fullscreen.setFlat(True)
        self.fullscreen.setObjectName("fullscreen")
        self.min = QtWidgets.QPushButton(self.winbutton)
        self.min.setGeometry(QtCore.QRect(100, 0, 51, 51))
        self.min.setText("")
        self.min.setFlat(True)
        self.min.setObjectName("min")
        self.close = QtWidgets.QPushButton(self.winbutton)
        self.close.setGeometry(QtCore.QRect(150, 0, 51, 51))
        self.close.setStyleSheet("")
        self.close.setText("")
        self.close.setFlat(True)
        self.close.setObjectName("close")
        self.close.raise_()
        self.min.raise_()
        self.fullscreen.raise_()
        self.help.raise_()
        self.searchbox = QtWidgets.QLineEdit(self.titlebar)
        self.searchbox.setGeometry(QtCore.QRect(4, 4, 621, 43))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.searchbox.setFont(font)
        self.searchbox.setObjectName("searchbox")
        self.pushButton = QtWidgets.QPushButton(self.titlebar)
        self.pushButton.setGeometry(QtCore.QRect(625, 4, 61, 43))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.main = QtWidgets.QFrame(self.di_ceng)
        self.main.setGeometry(QtCore.QRect(0, 50, 1481, 871))
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.op = QtWidgets.QWidget(self.main)
        self.op.setGeometry(QtCore.QRect(0, 0, 411, 871))
        self.op.setObjectName("op")
        self.useravatar = QtWidgets.QLabel(self.op)
        self.useravatar.setGeometry(QtCore.QRect(0, 0, 171, 161))
        self.useravatar.setText("")
        self.useravatar.setObjectName("useravatar")
        self.username = QtWidgets.QLabel(self.op)
        self.username.setGeometry(QtCore.QRect(170, 0, 241, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.userinfo = QtWidgets.QPushButton(self.op)
        self.userinfo.setGeometry(QtCore.QRect(170, 60, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.userinfo.setFont(font)
        self.userinfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userinfo.setObjectName("userinfo")
        self.userloginout = QtWidgets.QPushButton(self.op)
        self.userloginout.setGeometry(QtCore.QRect(170, 110, 241, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.userloginout.setFont(font)
        self.userloginout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.userloginout.setObjectName("userloginout")
        self.ctrlsrver = QtWidgets.QPushButton(self.op)
        self.ctrlsrver.setGeometry(QtCore.QRect(0, 160, 411, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.ctrlsrver.setFont(font)
        self.ctrlsrver.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ctrlsrver.setObjectName("ctrlsrver")
        self.history = QtWidgets.QPushButton(self.op)
        self.history.setGeometry(QtCore.QRect(0, 360, 411, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.history.setFont(font)
        self.history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history.setObjectName("history")
        self.settings = QtWidgets.QPushButton(self.op)
        self.settings.setGeometry(QtCore.QRect(0, 260, 411, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.settings.setFont(font)
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings.setObjectName("settings")
        self.guild = QtWidgets.QFrame(self.op)
        self.guild.setGeometry(QtCore.QRect(-1, 619, 411, 161))
        self.guild.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.guild.setFrameShadow(QtWidgets.QFrame.Raised)
        self.guild.setObjectName("guild")
        self.guildtext = QtWidgets.QLabel(self.guild)
        self.guildtext.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(22)
        self.guildtext.setFont(font)
        self.guildtext.setObjectName("guildtext")
        self.guildtext2 = QtWidgets.QLabel(self.guild)
        self.guildtext2.setGeometry(QtCore.QRect(10, 50, 401, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(True)
        self.guildtext2.setFont(font)
        self.guildtext2.setObjectName("guildtext2")
        self.more = QtWidgets.QFrame(self.op)
        self.more.setGeometry(QtCore.QRect(0, 780, 411, 91))
        self.more.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.more.setFrameShadow(QtWidgets.QFrame.Raised)
        self.more.setObjectName("more")
        self.about = QtWidgets.QLabel(self.more)
        self.about.setGeometry(QtCore.QRect(10, 60, 41, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setUnderline(True)
        self.about.setFont(font)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about.setObjectName("about")
        self.license = QtWidgets.QLabel(self.more)
        self.license.setGeometry(QtCore.QRect(220, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setUnderline(True)
        self.license.setFont(font)
        self.license.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.license.setObjectName("license")
        self.opear1 = QtWidgets.QLabel(self.main)
        self.opear1.setGeometry(QtCore.QRect(600, 0, 731, 491))
        self.opear1.setText("")
        self.opear1.setObjectName("opear1")
        self.tip1 = QtWidgets.QLabel(self.main)
        self.tip1.setGeometry(QtCore.QRect(530, 470, 851, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(48)
        self.tip1.setFont(font)
        self.tip1.setObjectName("tip1")
        self.open = QtWidgets.QPushButton(self.main)
        self.open.setGeometry(QtCore.QRect(530, 590, 231, 251))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.open.setFont(font)
        self.open.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open.setFlat(True)
        self.open.setObjectName("open")
        self.book = QtWidgets.QPushButton(self.main)
        self.book.setGeometry(QtCore.QRect(820, 590, 231, 251))
        self.book.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.book.setFont(font)
        self.book.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.book.setFlat(True)
        self.book.setObjectName("book")
        self.feedback = QtWidgets.QPushButton(self.main)
        self.feedback.setGeometry(QtCore.QRect(1110, 590, 231, 251))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.feedback.setFont(font)
        self.feedback.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback.setFlat(True)
        self.feedback.setObjectName("feedback")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close.clicked.connect(MainWindow.close) # type: ignore
        self.min.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.fullscreen.clicked.connect(MainWindow.showMaximized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MC_SEVER_GUI客户端"))
        self.di_ceng.setProperty("myclass", _translate("MainWindow", "di_ceng"))
        self.titlebar.setProperty("myclass", _translate("MainWindow", "titlebar"))
        self.help.setText(_translate("MainWindow", "  ？"))
        self.help.setProperty("myclass", _translate("MainWindow", "help"))
        self.fullscreen.setProperty("myclass", _translate("MainWindow", "fullscreen"))
        self.min.setProperty("myclass", _translate("MainWindow", "min"))
        self.close.setProperty("myclass", _translate("MainWindow", "close"))
        self.searchbox.setPlaceholderText(_translate("MainWindow", "搜索玩家,服务器..."))
        self.searchbox.setProperty("myclass", _translate("MainWindow", "searchbox"))
        self.pushButton.setProperty("myclass", _translate("MainWindow", "search"))
        self.main.setProperty("myclass", _translate("MainWindow", "main"))
        self.op.setProperty("myclass", _translate("MainWindow", "op"))
        self.useravatar.setProperty("myclass", _translate("MainWindow", "useravatar"))
        self.username.setText(_translate("MainWindow", "    123456"))
        self.username.setProperty("myclass", _translate("MainWindow", "username"))
        self.userinfo.setText(_translate("MainWindow", "        用户信息"))
        self.userinfo.setProperty("myclass", _translate("MainWindow", "userinfo"))
        self.userloginout.setText(_translate("MainWindow", "        退出登录"))
        self.userloginout.setProperty("myclass", _translate("MainWindow", "userloginout"))
        self.ctrlsrver.setText(_translate("MainWindow", "                  管理服务器"))
        self.ctrlsrver.setProperty("myclass", _translate("MainWindow", "ctrlsever"))
        self.history.setText(_translate("MainWindow", "        设置"))
        self.history.setProperty("myclass", _translate("MainWindow", "settings"))
        self.settings.setText(_translate("MainWindow", "               历史记录"))
        self.settings.setProperty("myclass", _translate("MainWindow", "history"))
        self.guildtext.setText(_translate("MainWindow", " 当前:"))
        self.guildtext.setProperty("myclass", _translate("MainWindow", "guildtext"))
        self.guildtext2.setText(_translate("MainWindow", "主页"))
        self.guildtext2.setProperty("myclass", _translate("MainWindow", "guildtext2"))
        self.about.setText(_translate("MainWindow", "关于..."))
        self.about.setProperty("myclass", _translate("MainWindow", "about"))
        self.license.setText(_translate("MainWindow", "许可证..."))
        self.license.setProperty("myclass", _translate("MainWindow", "license"))
        self.opear1.setProperty("myclass", _translate("MainWindow", "opear1"))
        self.tip1.setText(_translate("MainWindow", "emm....似乎这里没有内容..."))
        self.tip1.setProperty("myclass", _translate("MainWindow", "tip1"))
        self.open.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"创建/打开本地服务器"))
        self.open.setProperty("myclass", _translate("MainWindow", "open"))
        self.book.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"查看教程"))
        self.book.setProperty("myclass", _translate("MainWindow", "book"))
        self.feedback.setText(_translate("MainWindow", "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"反馈"))
        self.feedback.setProperty("myclass", _translate("MainWindow", "feedback"))
import kuhuduan_rc
